### ISSUE TITLE
The order of x-labels changes with the input

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tacApp#1]
* The labels on the x-axis change with the input. Is this expected? If
not what is the correct order?

``` r
devtools::load_all()
#> ℹ Loading tacApp

data1 <- prep_raw(full(), full()[1,])
#> Warning in min(data_portfolio$id): no non-missing arguments to min; returning
#> Inf
#> Warning in max(data_portfolio$id): no non-missing arguments to max; returning
#> -Inf
plot_techs(data1)
```

![](https://i.imgur.com/dda5QuK.png)

``` r
data2 <- prep_raw(full(), full()[40,])
plot_techs(data2)
```

![](https://i.imgur.com/Asn6stO.png)

<sup>Created on 2021-12-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>﻿

**Comment by maurolepore** [comment]
@Souad-2DII can you please comment?

**Comment by Souad-2DII** [comment]
@maurolepore 
The order shouldn't change.
Year 0 should always be on the extreme left and Year 1 should always be on the extreme right.
In between the most important is that the colors are correct (green for real - orange for virtual - grey for unidentified).
However, the grey bars (unidentified) should be after the green and orange ones.

**Comment by maurolepore** [comment]
Thanks! The colours seem always correct, and the order in the live app too. I'll close this issue after this comment. 

The reprex above shows incorrect order but I did it off an open PR (https://github.com/2DegreesInvesting/tacApp/pull/2) -- meaning that PR breaks the order. I'll need to fix it before merging.

For the record, this is the result from the `main` (live) branch:

``` r
devtools::load_all()
#> ℹ Loading tacApp
plot_techs(prep_raw(full(), full()[40,]))
```

![](https://i.imgur.com/WQQtM7R.png)

<sup>Created on 2021-12-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
