### ISSUE TITLE
When the real and virtual rows are empty (= 0) we display an error message.

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tacApp#3]
When the real and virtual rows are empty (= 0) we display the "no data on the selected technology" message.
As long as there is a value for one of these categories we display the plot (even if the values are super low).

_Originally posted by @Souad-2DII in https://github.com/2DegreesInvesting/tacApp/pull/2#issuecomment-1002121527_

**Comment by maurolepore** [comment]
@Souad-2DII, 

If the user selects a company and technology for which we have no data, the tab "View changes" now shows no table or plot and instead this message:

>  There is no data for the company and technology you selected.
> Do you need to search and select another row?

Note the tab "Download results" still shows a downloadable table. Should we instead also show a message and no table?

**Comment by Souad-2DII** [comment]
@maurolepore 
Yes we should do the same for the "Download results" tab. No table and a message. For consistency.

**Comment by maurolepore** [comment]
The new version of the app exposes only data that yields valid results. So no longer we need to handle bad inputs.
