### ISSUE TITLE
Should we precompute results?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tacApp#4]
https://github.com/2DegreesInvesting/tacApp/issues/3 handles bad inputs by asking the user to select a different row. But instead we could precompute results and plots for all rows in the input dataset and offer only valid options to the user. The benefits for the user are:

* The app feels more snappy because it does no computation at all (we store the precomputed results).
* The user gets faster to what they want.

@Souad-2DII does this sound like a good idea?

**Comment by Souad-2DII** [comment]
@maurolepore 
Sounds like a good thing! To avoid any lag due to computation.
